let stockProductos = [
    {id: 1, nombre: "Academia Belladonna", autor: "Pablo De Santis", precio: 1940, img: 'public/img/standalone/academia_belladonna.png', cantidad: 1, categoria: "M"},
    {id: 2, nombre: "Beautiful Disaster", autor: "Jamie McGuire", precio: 2898, img: 'public/img/standalone/beautiful_disaster.jpg', cantidad: 1, categoria: "YA" },
    {id: 3, nombre: "Fangirl", autor: "Rainbow Rowell", precio: 1998, img: 'public/img/standalone/fangirl.jpg', cantidad: 1, categoria: "YA" },
    {id: 4, nombre: "It Ends With Us", autor: "Collen Hoover", precio: 3988, img: 'public/img/standalone/it_ends_with_us.jpg', cantidad: 1, categoria: "YA" },
    {id: 5, nombre: "Kingpin", autor: "W.S. Greer", precio: 798, img: 'public/img/standalone/kingpin_an_italian_mafia_romance_duet.jpg', cantidad: 1, categoria: "RM" },
    {id: 6, nombre: "Make It Sweet", autor: "Kristen Callihan", precio: 2590, img: 'public/img/standalone/make_it_sweet.jpg', cantidad: 1, categoria: "YA" },
    {id: 7, nombre: "Our Overtime", autor: "S.C. Kate", precio: 2598, img: 'public/img/standalone/our_overtime.jpg', cantidad: 1, categoria: "YAD" },
    {id: 8, nombre: "Rhythm, Chord & Malykhin", autor: "Mariana Zapata", precio: 2998, img: 'public/img/standalone/rhythm_chord_and_malykhin.jpg', cantidad: 1, categoria: "YAM" },
    {id: 9, nombre: "The Cheat Sheet", autor: "Sarah Adams", precio: 998, img: 'public/img/standalone/the_cheat_sheet.jpg', cantidad: 1, categoria: "YAD" },
    {id: 10, nombre: "The Ex Hex", autor: "Erin Sterling", precio: 2798, img: 'public/img/standalone/the_ex_hex.jpg', cantidad: 1, categoria: "YAF" },
    {id: 11, nombre: "The Hating Game", autor: "Sally Thorne", precio: 1798, img: 'public/img/standalone/the_hating_game.jpg', cantidad: 1, categoria: "YA" },
    {id: 12, nombre: "The Love Hypothesis", autor: "Ali Hazelwood", precio: 3200, img: 'public/img/standalone/the_love_hypothesis.jpg', cantidad: 1, categoria: "YA" },
    {id: 13, nombre: "The Off Limtis Rule", autor: "Sarah Adams", precio: 2600, img: 'public/img/standalone/the_off_limits_rule.jpg', cantidad: 1, categoria: "YA" },
    {id: 14, nombre: "The Spanish Love Deception", autor: "Elena Armas", precio: 3000, img: 'public/img/standalone/the_spanish_love_deception.jpg', cantidad: 1, categoria: "YA" },
    {id: 15, nombre: "The Sweetest Oblivion", autor: "Danielle Lori", precio: 3600, img: 'public/img/standalone/the_sweetest_oblivion.jpg', cantidad: 1, categoria: "RM" },
    {id: 16, nombre: "The Unhoneymooners", autor: "Christina Lauren", precio: 2898, img: 'public/img/standalone/the_unhoneymooners.jpg', cantidad: 1, categoria: "YA" },
    {id: 17, nombre: "The Upside of Falling", autor: "Alex Light", precio: 3200, img: 'public/img/standalone/the_upside_of_falling.jpg', cantidad: 1, categoria: "YA" },
    {id: 18, nombre: "Stalking Jack The Ripper", autor: "Kerri Maniscalco", precio: 2198, img: 'public/img/stalking-jack-the-ripper/stalkin_jack_the_ripper.jpg', cantidad: 1, categoria: "MR" },
    {id: 19, nombre: "Hunting Prince Dracula", autor: "Kerri Maniscalco", precio: 2198, img: 'public/img/stalking-jack-the-ripper/hunting_prince_dracula.jpg', cantidad: 1, categoria: "MR" },
    {id: 20, nombre: "Escaping from Houdini", autor: "Kerri Maniscalco", precio: 2198, img: 'public/img/stalking-jack-the-ripper/escaping_from_houdini.jpg', cantidad: 1, categoria: "MR" },
    {id: 21, nombre: "Capturing the Devil", autor: "Kerri Maniscalco", precio: 2198, img: 'public/img/stalking-jack-the-ripper/capturing_the_devil.jpg', cantidad: 1, categoria: "MR" },
    {id: 22, nombre: "Throttled", autor: "Lauren Asher", precio: 3000, img: 'public/img/dirty-air/1_throttled.jpg', cantidad: 1, categoria: "YAD" },
    {id: 23, nombre: "Collided", autor: "Lauren Asher", precio: 3000, img: 'public/img/dirty-air/2_collided.jpg', cantidad: 1, categoria: "YAD" },
    {id: 24, nombre: "Wrecked", autor: "Lauren Asher", precio: 3000, img: 'public/img/dirty-air/3_wrecked.jpg', cantidad: 1, categoria: "YAD" },
    {id: 25, nombre: "Redeemed", autor: "Lauren Asher", precio: 3000, img: 'public/img/dirty-air/4_redeemed.jpg', cantidad: 1, categoria: "YAD" },

]